from typing import List
import numpy as np


def explained_variance_error(x_simulated: List[float], y_real: List[List[float]]) -> str:
    # convert python list into numpy array for faster computation of error
    x_simulated = np.array(x_simulated)
    y_real = np.array(y_real)

    return np.sum(np.sqrt(np.power(x_simulated - y_real, 2))) / np.sum(
        np.sqrt(np.power(y_real - np.mean(y_real), 2))
    )


if __name__ == "__main__":
    simulated = [
        635.89,
        1220.35,
        2242.8,
        4257.43,
        6591.92,
        9817.08,
        12623.81,
        14725.45,
        6963.59,
        7235.83,
        7483.12,
        13444.28,
        17224.0,
        24256.91,
        15627.19,
        15644.88,
        21096.64,
        21104.28,
        21108.32,
        21110.0,
        21110.83,
        21111.28,
        21111.5,
    ]
    real = [
        [
            600.89,
            1220.35,
            2242.8,
            4257.43,
            6591.92,
            9817.08,
            12623.81,
            14725.45,
            6963.59,
            7235.83,
            7483.12,
            13444.28,
            17224.0,
            24256.91,
            15627.19,
            15644.88,
            21096.64,
            21104.28,
            21108.32,
            21110.0,
            21110.83,
            21111.28,
            21111.5,
        ],
        [
            635.89,
            1220.35,
            2242.8,
            4257.43,
            61.92,
            9817.08,
            12623.81,
            14725.45,
            6963.59,
            7235.83,
            7483.12,
            13444.28,
            17224.0,
            24256.91,
            15627.19,
            1568,
            21096.64,
            21104.28,
            21108.32,
            21110.0,
            21110.83,
            21111.28,
            21111.5,
        ],
        [
            635.89,
            1220.35,
            2242.8,
            4257.43,
            6591.92,
            9817.08,
            12623.81,
            14725.45,
            6963.59,
            7235.83,
            7483.12,
            13444.28,
            17224.0,
            24256.91,
            15627.19,
            15644.88,
            21096.64,
            21104.28,
            21108.32,
            21110.0,
            21110.83,
            21111.28,
            21111.5,
        ],
        [
            635.89,
            1220.35,
            2242.8,
            4257.43,
            6591.92,
            9817.08,
            12623.81,
            14725.45,
            6963.59,
            7235.83,
            7483.12,
            13444.28,
            17224.0,
            24256.91,
            15627.19,
            15644.88,
            21096.64,
            21104.28,
            21108.32,
            21110.0,
            21110.83,
            21111.28,
            21111.5,
        ],
        [
            635.89,
            1220.35,
            2242.8,
            4257.43,
            6591.92,
            9817.08,
            12623.81,
            14725.45,
            6963.59,
            7235.83,
            7483.12,
            13444.28,
            17224.0,
            24256.91,
            15627.19,
            15644.88,
            21096.64,
            21104.28,
            21108.32,
            21110.0,
            21110.83,
            21111.28,
            21111.5,
        ],
    ]

    error = explained_variance_error(simulated, real)

    print("Error: ", error)
